services:
  backend:
    container_name: gnss-backend
    build:
      context: ./web/backend/backend
      args:
        USER_ID_TO_SAVE_FILES: ${USER_ID_TO_SAVE_FILES}
        GROUP_ID_TO_SAVE_FILES: ${GROUP_ID_TO_SAVE_FILES}
    volumes:
      - ./web/backend/backend/backend_django_project/logs:/code/backend_django_project/logs
      - ${MEDIA_FOLDER_HOST_PATH}:/code/backend_django_project/media
    restart: always
    env_file:
      - .env

  frontend:
    container_name: gnss-frontend
    build:
      context: ./web/frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    driver: bridge
    